### ISSUE TITLE
[Bug]: Router randomly stops showing views on navigation

### ISSUE THREAD

**Issue by Leon99** [reactiveui/splat#1027]
### Describe the bug 🐞

Routing stops showing views on the second (and further) navigation to the same view instance.

### Reproduction repository

https://github.com/Leon99/AvaRxUI.git

### Expected behavior

Routing shows views on the second (and further) navigation to the same view instance.

### Screenshots 🖼️

![AvaRxUI_cJYj9zGyv9](https://github.com/reactiveui/ReactiveUI/assets/6840381/ee2030a5-452d-4862-a7d9-5f2c04394e75)

### IDE

Rider Windows

### Operating system

Windows 11

### ReactiveUI Version

19.4.1

### Additional information ℹ️

Same code works fine using Avalonia's built-in routing.
Same code works fine if view instances are not reused (registered as not a singleton).
Same code works fine when using Splat service locator.

**Comment by glennawatson** [comment]
As discussed in #1028 this is a known Avalonia bug. Follow up there.

**Comment by Leon99** [comment]
Thanks for the investigation @ChrisPulman!
I'm confused though - if https://github.com/AvaloniaUI/Avalonia/issues/12333 is the root cause, then how come the issue is not reproduced when using `TransitioningContentControl` directly, and also not reproduced when only Splat is used for IoC?

**Comment by Leon99** [comment]
...with that said, setting `PageTransition="{x:Null}"` fixes the issue.

**Comment by ChrisPulman** [comment]
I was able to reproduce the error when using any of the DI's the page transition animation is the root of the issue, there's an open bug in Avalonia which matches the exact issue being observed. If you set the transition to null this will disable the transition and therefore not fail.
