### ISSUE TITLE
WPF, .net 8.0 and Splat latest version: IBitmap.ToNative, FromNative, SplatColor.ToNativeBrush and SplatColor.FromNativeColor not found by compiler.

### ISSUE THREAD

**Issue by kgday** [reactiveui/splat#1068]
Please note although we can't commit to any timeline, priority will be given to those who are [Contributors](https://github.com/reactiveui/splat#contribute ) to the project.

If this is a question please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/splat).

**Describe the bug**
After upgrading to a wpf application to .net 8.0 and to the latest version of splat and splat.drawing, IBitmap.ToNative ,IBitmap.FromNative, SplatColor.ToNativeBrush and SplatColor.FromNativeColor not found by compiler.  

Splat version 14.8.12

Downgrading to 14.8.6 then gives me runtime errors with IBitmapLoader not able to be resolved.  I don't know if this is related to: https://github.com/reactiveui/ReactiveUI/issues/3696

**Comment by ChrisPulman** [comment]
Please ensure that you are targeting at least windows10.0.17763.0 
- `<TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>`

**Comment by kgday** [comment]
Thank you, that was the problem.
