### ISSUE TITLE
Exception logging improvements

### ISSUE THREAD

**Issue by Hinidu** [reactiveui/splat#120]
Hi! I have a little proposal for splat-2 logging facilities:
What do you think about replacing `IFullLogger` methods like this

``` csharp
void ErrorException([Localizable(false)] string message, Exception exception);
```

by methods like this

``` csharp
void Error(Exception exception, [Localizable(false)] string message, params object[] args);
```

In my opinion it has two advantages: 1) there is no need to use `String.Format` inside `ErrorException` call and actual formatting could be done by wrapped logging library (that is quite important for [Serilog](http://serilog.net/)) and 2) these methods don't need `Exception` suffix.

**Comment by RLittlesII** [comment]
In order to satisfy the following:
> formatting could be done by wrapped logging library

We'll have to expose a method on the `ILogger` interface something like below so the inner library can properly handle the formatting.
```csharp
void Write(Exception exception, [Localizable(false)] string message, LogLevel logLevel, params object[] args);
```

**Comment by dpvreony** [comment]
with #228 in mind do you want ILogger having 

```
params object[] args
```

**Comment by RLittlesII** [comment]
No, I would not.  This would change to the parameterized approach discussed.
