### ISSUE TITLE
Splat.ModeDetector.InUnitTestRunner() does not detect NCrunch

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/splat#132]
See https://github.com/reactiveui/ReactiveUI/issues/1089#issuecomment-198689138

**Comment by ryanwersal** [comment]
I was poking around at some of the up-for-grabs issues and I believe this is resolved with commit f14fda195c93958e0e028befa553eb7ea622278a.

**Comment by glennawatson** [comment]
Resolved by f14fda195c93958e0e028befa553eb7ea622278a.
