### ISSUE TITLE
Provide the Locator with a UnRegister<T> option to enable cleanup of unused instances

### ISSUE THREAD

**Issue by ChrisPulman** [reactiveui/splat#134]
Hi Paul,
When writing dynamic applications it is often needed to remove instances created with IoC
// Create a new named instance of Toaster
Locator.CurrentMutable.Register(() => new Toaster(), typeof(IToaster), "Toaster1");

// Use the toaster
var toaster1 = Locator.Current.GetService<IToaster>("Toaster1");
toaster1.Make();
toaster1.DoThings();

// Remove the named instance Toaster1 
Locator.Current.UnRegister<IToaster>("Toaster1");

Please can you consider adding this functionality to the Splat Locator

**Comment by glennawatson** [comment]
Thanks @chrispullman. Been a while but might as well get this one out hey.
