### ISSUE TITLE
Type resolution not working on Mac

### ISSUE THREAD

**Issue by verybadcat** [reactiveui/splat#138]
I can't get types such as RectangleF, Point, etc. to resolve to themselves from a PCL to a Mac project. I don't know if this is a splat issue, a Xamarin issue, or a me issue. I've done a writeup of this on SO here:

http://stackoverflow.com/questions/37880335/type-resolution-with-splat-library-and-xamarin-mac

**Comment by ghuntley** [comment]
This needs to be checked as part of #159

**Comment by ghuntley** [comment]
Resolved in #159
