### ISSUE TITLE
Splat Meeting Minutes - 8th of July 2016

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/splat#139]
# In attendance
- Paul Betts
- Brendan Forster
- Kent Boogart
- Oren Novotny
- Geoffrey Huntley
- Dennis Daume
- Michael Stonis
# With Apologies
- Paul Betts, as we bait and switched him with the promise of a social occasion with beer.
# The Plan
## SemVer
- Oren proposed that we adopt the .NET SemVer guidelines and there were no objections. We will move forward and adopt https://docs.microsoft.com/en-us/dotnet/articles/core/versions/index#semantic-versioning for ReactiveUI and all sister projects. - https://github.com/reactiveui/ReactiveUI/issues/1134
## Splat
- Netstandard will be adopted.
- The major number will be bumped in the next release (needed because of netstandard)
- The continuous integration pipeline will be lifted from ReactiveUI and brought across to the Splat project - https://github.com/paulcbetts/splat/issues/140

**Comment by ethanhs** [comment]
Is there a timeline for when you will adopt netstandard? I was working on bringing Avalonia over to netstandard, and it has a dependency on splat.

**Comment by shiftkey** [comment]
Has it really been that long? Ugh, let me give this a shot tonight/tomorrow and see if I can get a PR opened.

**Comment by aalmada** [comment]
Does this mean ReactiveUI 7 has been waiting for this all this time? :/
https://github.com/reactiveui/ReactiveUI/issues/1132
