### ISSUE TITLE
IOS Image Loading only on Main thread

### ISSUE THREAD

**Issue by andreballot** [reactiveui/splat#141]
When using **splat** in an IOS App (build with Xamarin) to download images in the background (while the UI should be responsive), invoking the following line in a separate thread still causes the UI to become very unresponsive:

`BitmapLoader.Current.Load(Stream, null, null)`

Going to the **splat** IOS implementation, I do indeed see the following, which means part of the loading happens on the main thread:

`UIApplication.SharedApplication.InvokeOnMainThread(() => {`

Any reason for this at all? I want to do a Load and Save of an image on whatever thread is calling it.

Should I extend the classes myself or add an overload for the project?

Thanks very much!

**Comment by glennawatson** [comment]
This is being tracked by https://github.com/reactiveui/splat/issues/161
