### ISSUE TITLE
Use corefx 2D geometry primitives?

### ISSUE THREAD

**Issue by kentcb** [reactiveui/splat#142]
Splat bundles the mono implementation for `Point`, `Rectangle`, `Size`, and their float-based counterparts. Should it instead bundle [the corefx implementation](https://github.com/dotnet/corefx/tree/master/src/System.Drawing.Primitives/src/System/Drawing) now? Might make sense as mono assumes more and more code from corefx.

**Comment by kentcb** [comment]
Actually, not sure this is of any consequence at all, because bait-and-switch will always prefer the platform implementation, right? Is there a reason Splat includes the entire source rather than just stubbing out the APIs?

**Comment by ghuntley** [comment]
:fire: netstandard will save us all!
