### ISSUE TITLE
Migrate to netstandard/vs2017 csproj

### ISSUE THREAD

**Issue by olevett** [reactiveui/splat#153]
***Note*: for support questions, please ask on StackOverflow: https://stackoverflow.com/questions/tagged/splat . This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Targets PCL platforms

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**What is the expected behavior?**
Targeting netstandard, using new csproj files.

**What is the motivation / use case for changing the behavior?**
Better support going forward, better developer experience for xplat.

**Which versions of Splat, and which platform / OS are affected by this issue? Did this work in previous versions of Splat? Please also test with the latest stable and snapshot (https://www.myget.org/feed/Splat/package/nuget/Splat) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by NZSmartie** [comment]
I've had a go at this, and can only convert the net standard and .Net 45 projects to the new dotnet csproj file format (i've even merged them into the one csproj file).

WinRT, Xmaring.iOS, Xamarin.macOS and MonoAndroid all are nto supported as there are no TargetFramework definitions inside Microsoft's new dotnet core SDK. 

The only work around I can see without waiting for official support is to create our own MSBuild tasks, or perform some MSBuild sourcery (pun intended).

**Comment by NZSmartie** [comment]
See https://github.com/NZSmartie/splat/tree/feature/csproj

**Comment by Cheesebaron** [comment]
@NZSmartie I think @onovotny has some of this magic in a nuget package and some samples in one of his repos.

**Comment by ghuntley** [comment]
This is being worked on over at https://github.com/reactiveui/splat/pull/159

**Comment by ghuntley** [comment]
Resolved in #159
