### ISSUE TITLE
Problem updating from 1.6.2 to 2.0.0 through Nuget

### ISSUE THREAD

**Issue by grantkiwi** [reactiveui/splat#156]
***Note*: for support questions, please ask on StackOverflow: https://stackoverflow.com/questions/tagged/splat . This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Cannot install through nuget

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Update from Splat 1.6.2 to 2.0.0

**What is the expected behavior?**
Install latest version 2.0.0

**What is the motivation / use case for changing the behavior?**

**Which versions of Splat, and which platform / OS are affected by this issue? Did this work in previous versions of Splat? Please also test with the latest stable and snapshot (https://www.myget.org/feed/Splat/package/nuget/Splat) versions.**
Currrently using 1.6.2

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Splat 2.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile49', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by grantkiwi** [comment]
Attempting to gather dependency information for package 'Splat.2.0.0' with respect to project 'TimeFilerUIClock', targeting '.NETPortable,Version=v4.5,Profile=Profile49'
Gathering dependency information took 2.9 sec
Attempting to resolve dependencies for package 'Splat.2.0.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Splat.2.0.0'
Resolved actions to install package 'Splat.2.0.0'
Retrieving package 'Acr.UserDialogs 6.5.0' from 'nuget.org'.
Found package 'Splat 2.0.0' in 'C:\VSS\picassomobile\TimeFilerNative\TimeFilerUIClock\packages'.
Removed package 'Acr.UserDialogs.6.4.1' from 'packages.config'
Successfully uninstalled 'Acr.UserDialogs.6.4.1' from TimeFilerUIClock
Removed package 'Splat.1.6.2' from 'packages.config'
Successfully uninstalled 'Splat.1.6.2' from TimeFilerUIClock
Install failed. Rolling back...
Package 'Splat.2.0.0' does not exist in project 'TimeFilerUIClock'
Package 'Splat.1.6.2' already exists in folder 'C:\VSS\picassomobile\TimeFilerNative\TimeFilerUIClock\packages'
Added package 'Splat.1.6.2' to 'packages.config'
Package 'Acr.UserDialogs.6.4.1' already exists in folder 'C:\VSS\picassomobile\TimeFilerNative\TimeFilerUIClock\packages'
Added package 'Acr.UserDialogs.6.4.1' to 'packages.config'
Executing nuget actions took 6.56 sec
Could not install package 'Splat 2.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile49', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
Time Elapsed: 00:00:09.5731495
========== Finished ==========

**Comment by Cheesebaron** [comment]
Nuspec specifies: Portable-Win81+Wpa81

The PCL you are installing in is Portable-WP8

Change your PCL profile or switch to NET Standard.

**Comment by grantkiwi** [comment]
Hi

I need to use Windows silverlight as my app talks to a wcf service

Why did you drop support in latest version?

I'm sure this will affect lots of users?

Look forward to your reply

Cheers
Grant

________________________________

**Comment by Cheesebaron** [comment]
Windows Phone 8.0 and Windows Phone 8.1 are end of support. Either stick to an old version that has WP8 support, or move along to a market that is more than 1%...

**Comment by logikonline** [comment]
@Cheesebaron If you understood what a nightmare it is to remove those you may be slightly cooler.  We cannot simply remove those and some of us are running huge projects and the BS about uninstalling every stupid reference to remove it is BS.

add the dam references back for a library with no dependencies.
