### ISSUE TITLE
iOS: The type 'Color' is defined in an assembly that is not referenced.

### ISSUE THREAD

**Issue by cabauman** [reactiveui/splat#176]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Trying to access colors from an iOS project that are defined in a netstandard lib results in a compile error.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
- Create a new solution with a netstandard class library and an iOS project.
- Add ReactiveUI prerelease 8.0.0-alpha0117 to both projects.
- Create a color property in the netstandard project:

```
public static System.Drawing.Color Red
{
    get { return System.Drawing.Color.Red; }
}
```

_Compile error:_ The type 'Color' exists in both 'Splat, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

- Update Splat from v2.0.0 to v3.0.0 in both projects.
- _Error goes away_
- Access that color from the iOS project:

```
public override void ViewDidLoad()
{
    base.ViewDidLoad();
    var redColor = Class1.Red;
}
```

_Compile error:_ The type 'Color' is defined in an assembly that is not referenced. You must add a reference to assembly 'OpenTK-1.0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.

- Add a reference to OpenTK-1.0.
- _Error goes away_
- Add a call to ToNative:

`var redColor = Class1.Red.ToNative();`

_Compile error:_ 'Color' does not contain a definition for 'ToNative' and no extension method 'ToNative' accepting a first argument of type 'Color' could be found (are you missing a using directive or an assembly reference?)

**What is the expected behavior?**
Colors defined in the netstandard lib are accessible from the iOS project.

**What is the motivation / use case for changing the behavior?**
So we can define colors in a central location and use the ToNative extension method.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**
ReactiveUI prerelease 8.0.0-alpha0117

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
An Android project is able to access the netstandard colors with no issue.

**Comment by albilaga** [comment]
I create the repo in here https://github.com/albilaga/SplatColor

**Comment by glennawatson** [comment]
Do any of you two guys want to try tackling this one?

**Comment by cabauman** [comment]
Yeah, I'll give it another shot.

**Comment by cabauman** [comment]
How about defining a simple Splat.Color struct and implementing implicit operators for _to_ and _from_ System.Drawing.Color?

        public static implicit operator System.Drawing.Color(SplatColor splatColor)
        {
            ...
            return color;
        }

        public static implicit operator SplatColor(System.Drawing.Color color)
        {
            ...
            return splatColor;
        }

Then in client class libraries we can simply do something like this:

    public static class Colors
    {
        public static Splat.Color MyRed => System.Drawing.Color.Red
    }

and in the platform project

`UIColor color = ClassLibrary.Colors.MyRed.ToNative()`

This avoids the needs to manually map all the System.Drawing colors like in the current shim.

Tried it in my local branch and works good for the iOS project I was having trouble with. Anyone see any downsides to this approach?

**Comment by albilaga** [comment]
looks good to me.

**Comment by albilaga** [comment]
Looks good for me. Maybe try to create PR @cabauman ?

**Comment by cabauman** [comment]
@albilaga I went a little different route than described above, but made a PR.
