### ISSUE TITLE
Join the .NET Foundation

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/splat#181]
Splat is a critical dependency of ReactiveUI. It's not big enough to stand on its own two feet but the maintainers of ReactiveUI need to ensure that the intellectual property and copyright is secured.

The top commits are as follows:

![image](https://user-images.githubusercontent.com/127353/39742896-84de172a-52e2-11e8-9aad-9bf7e3b00055.png)

Next steps is to obtain approval from:

- [x] @paulcbetts 
- [x] @ghuntley
- [x] @olevett 
- [x] @rzhw 
- [x] @flagbug

**Comment by olevett** [comment]
Sounds good to me :)

**Comment by rzhw** [comment]
Likewise :+1:

**Comment by flagbug** [comment]
@ghuntley Let's do this!

**Comment by ghuntley** [comment]
Next steps - email dotnet foundation, ask them to send the paperwork to the above parties via DocuSign. Done.
