### ISSUE TITLE
NuGet problem: Failed to add reference

### ISSUE THREAD

**Issue by SpiegelSoft** [reactiveui/splat#184]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

I cannot add Splat as a dependency to an F# Xamarin Android class library

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Visual Studio 2017

Create a new Xamarin Android class library (File -> New Project -> Visual F# -> Android -> Class Library (Android)

In the Package Manager Console, type "install-package Splat"

The installation fails with the following report:

Attempting to gather dependency information for package 'Splat.4.0.0' with respect to project 'ClassLibrary2', targeting 'MonoAndroid,Version=v8.1'
Gathering dependency information took 3.86 ms
Attempting to resolve dependencies for package 'Splat.4.0.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Splat.4.0.0'
Resolved actions to install package 'Splat.4.0.0'
Retrieving package 'Splat 4.0.0' from 'nuget.org'.
Adding package 'Splat.4.0.0' to folder 'c:\users\white\source\repos\ClassLibrary2\packages'
Added package 'Splat.4.0.0' to folder 'c:\users\white\source\repos\ClassLibrary2\packages'
Install failed. Rolling back...
Package 'Splat.4.0.0' does not exist in project 'ClassLibrary2'
Removing package 'Splat.4.0.0' from folder 'c:\users\white\source\repos\ClassLibrary2\packages'
Removed package 'Splat.4.0.0' from folder 'c:\users\white\source\repos\ClassLibrary2\packages'
Executing nuget actions took 1.46 sec
install-package : Failed to add reference. The package 'Splat' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the 
package. Please contact the package owners for assistance.
  Object reference not set to an instance of an object.
At line:1 char:1
+ install-package Splat
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:01.5428596

**What is the expected behavior?**

Splat should install

**What is the motivation / use case for changing the behavior?**

It can't install

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

Splat 4.0.0
Visual Studio 2017
Windows 10

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

I had a similar issue in my NuGet package, XamarinForms.Reactive.FSharp. It includes a library called GeographicLib.FSharp, which referenced an old version of Newtonsoft.Json. That old version had a reference to Microsoft.CSharp. In this case, adding a reference to the latest Newtonsoft.Json (which didn't reference Microsoft.CSharp) fixed the issue (it was complaining about a missing GAC reference to Microsoft.CSharp). I know that doesn't apply in this case, but it may be useful as background.

**Comment by ghuntley** [comment]
Jeeze that's no good. Not sure what's going on there but we ❤️ fsharp over here in Rx land. This definitely a scenario that needs resolving.

**Comment by SpiegelSoft** [comment]
On the iOS side it's perfectly fine. I'm pretty sure it's something to do with the Android template. The Xamarin Android boys are saying it's a NuGet issue.

**Comment by SpiegelSoft** [comment]
It seems that something like this is affecting ReactiveUI as well.

**Comment by SpiegelSoft** [comment]
It looks like this was happening due to a bug in the Xamarin template. I can't reproduce it in VS 17.0.2.

**Comment by ghuntley** [comment]
Thx for the update.
