### ISSUE TITLE
Add adapters to common logging frameworks

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/splat#232]
Lets add some adapters to common logging frameworks.

Given the community got impatient with us, we should come up with a naming scheme.

Eg like `Splat.LogAdapters.Serilog`

Common frameworks I can think of are:

- [x] Serilog #252
- [x]  NLog #236
- [x]  Log4Net #243 

Any others?

**Comment by dpvreony** [comment]
will do :)

**Comment by glennawatson** [comment]
@dpvreony The user you want to assign nuget packages to btw is "reactiveui"

**Comment by dpvreony** [comment]
ownership transferred. will get on with the log4net piece. will also review the targeting on the nlog one. I can't recall if it was I was working on a machine without android or if it genuinely didn't restore and build on mac.

**Comment by glennawatson** [comment]
I noticed in the NLog releases that it wasn't until version https://github.com/NLog/NLog/releases/tag/v4.5.7 until xamarin was supported.

**Comment by dpvreony** [comment]
Any objection to extending ILogger so the raw Exception remains available to the logging framework?

https://github.com/dpvreony/splat/blob/e59b6f5e83a98b2a6f406812b34cfc256fbec386/src/Splat/Logging/ILogger.cs

**Comment by glennawatson** [comment]
We been wanting to adapt this issue for Splat v7 (since it's a breaking change), would this do the trick for you?

https://github.com/reactiveui/splat/issues/120

**Comment by glennawatson** [comment]
btw our v7 issues we have planned to include https://github.com/reactiveui/splat/projects/1

**Comment by dpvreony** [comment]
yep #120 makes sense. i'll tweak the order to the change I just made on ilogger to accomodate

**Comment by glennawatson** [comment]
@dpvreony  If you are going to do #120 I guess we should just dump all the logging out in one full swoop for v7.

We have a MyGet if you need access for your own internal development sooner.

**Comment by glennawatson** [comment]
This has been completed by a number of different PRs
