### ISSUE TITLE
NLogLogger should not modify all logging-rules

### ISSUE THREAD

**Issue by snakefoot** [reactiveui/splat#245]
https://github.com/reactiveui/splat/blob/7034d3f2c88201023b7be2aadbdd6db7840e7274/src/Splat.NLog/NLogLogger.cs#L45

Instead it should just work like the `Log4NetLogger`

**Comment by dpvreony** [comment]
yeah I was thinking it was bit of an untidy way to do it

**Comment by glennawatson** [comment]
Want to take care of that @dpvreony?

**Comment by dpvreony** [comment]
yep on it

**Comment by snakefoot** [comment]
Resolved with #247
