### ISSUE TITLE
discussion: should ILogger.Level be a read only property?

### ISSUE THREAD

**Issue by dpvreony** [reactiveui/splat#246]
**Do you want to request a *feature* or report a *bug*?**

Bug \ Usability Issue.

**What is the current behavior?**

There's a disconnect between the ILogger log level and any target adapter log level. Both have to be at the right level in order for it to work.
Currently you can set the ILogger level. but it's independent of the adapter.
Splat.NLog was adjusting the loglevel but it was a bit of a forceful way to do things.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Set Log4Net\NLog\Serilog at Info.
Set ILogger at Debug.
Developer would expect it to write away. It won't.

**What is the expected behavior?**

Consistency of logging. Is there a use case for changing the loglevel at the ILogger level?

**What is the motivation / use case for changing the behavior?**

Developer experience.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by glennawatson** [comment]
The only use case I can think of is those func based operators that don't execute unless the log level is correct.

**Comment by dpvreony** [comment]
have done the concept work around it. questions on whether it would need the event handlers and disposable pattern etc.

**Comment by RLittlesII** [comment]
@dpvreony If the internal loggers support the event handlers then that's fine.  We could create observables over the event pattern, but in this case that may be overkill.  So I would say the event handler should be sufficient.
