### ISSUE TITLE
housekeeping: Dependabot config

### ISSUE THREAD

**Issue by dpvreony** [reactiveui/splat#254]
**Is your feature request related to a problem? Please describe.**

I was looking at the dependabot config around.

"in order not to constrain devs. ignore minor increments, unless it's a security update"

**Describe the solution you'd like**

Agree what reasonable versions are for the nlog, serilog, log4net, etc. and have dependabot work with those respecting major versions and security updates may need work. although we have very light touches on each of those frameworks.

**Describe alternatives you've considered**

**Describe suggestions on how to achieve the feature**

I know you can put version restrictions in the yml or set to take security updates as flagged on CVE. I think the security one becomes an exclusive setting though. I haven't tested I'm just sharing research and thoughts so far.

**Additional context**

https://dependabot.com/blog/introducing-config-files/

**Comment by glennawatson** [comment]
I tend to do dependabot updates once every major dot release of our product unless it's a minor update like that log4net where it was exclusively bug fixes. Eg it's why I have that nlog one there and will wait til splat 8. Nice thing is it shows you the change log. 

Issue with only critical updates that doesn't tend to work with dot net and less known packages.

**Comment by dpvreony** [comment]
yeah it was more a research piece. thought i'd record it as what I found

**Comment by glennawatson** [comment]
Worth putting a yaml config in anyway. I tend to prefer everything repo controlled so it's more community run
