### ISSUE TITLE
Microsoft.Extensions.Logging support

### ISSUE THREAD

**Issue by dpvreony** [reactiveui/splat#255]
**Is your feature request related to a problem? Please describe.**

This is a "play nice with others" idea. If a dev is already using the Microsoft logging interface and has it setup. Allow it to "just work".

In the world of netstandard and webassembly this might be a beneficial approach as well.

**Describe the solution you'd like**

Add equivalent Splat package for this Logging Middleware

**Describe alternatives you've considered**

**Describe suggestions on how to achieve the feature**

Need to do another package. Might be easier to test with serilog than nlog and log4net as the appenders for those assume xml config.

Splat -> MS Logging -> Serilog (or test package below)

**Additional context**

https://www.nuget.org/packages/Microsoft.Extensions.Logging
https://www.nuget.org/packages/DotNet.Extensions.Logging.Testing/

**Comment by glennawatson** [comment]
Fixed by #278
