### ISSUE TITLE
Skip delegate capture when doing LogLevel mapping for Serilog + NLog

### ISSUE THREAD

**Issue by snakefoot** [reactiveui/splat#260]
System.Linq + delegate-capture generates allocation, and unnecessary overhead.

See #259 as example of code-change.

Btw. if performance is really important, then a switch-statement is much faster than an array-lookup.

**Comment by glennawatson** [comment]
As discussed this is going to require proper benchmarking before proceeding. In future remember to not to discuss on a already closed PR code changes, just open a issue so we can be on a common approach.

**Comment by snakefoot** [comment]
I will await your benchmarks then.

**Comment by glennawatson** [comment]
I will be benchmarking the following scenarios:
1. Delegate capture approach with Linq
2. foreach approach
3. ImmutableDictionary
4. Dictionary (not a fan of this one because by their nature they are mutable and code maintainers could mis-use in the future)

**Comment by snakefoot** [comment]
Please also add a simple switch on the enum-value.

**Comment by glennawatson** [comment]
Sure..

**Comment by glennawatson** [comment]
Might not be today with the benchmarks btw. Because we use Msbuild.Sdk.Extras just making some alterations to the BenchmarkDotNet project.

**Comment by glennawatson** [comment]
Both of those should be addressed in recent PR's. 

Thanks snakefoot for your input.

**Comment by glennawatson** [comment]
Don't believe the int casting is required in this case. Since ImmutableDictionary does not use GetHashCode() for it's implementation, instead is implemented using a Avl tree.

**Comment by glennawatson** [comment]
Fixed by #263 and #262
