### ISSUE TITLE
[BUG] Thread Safety of MemoizingMRUCache

### ISSUE THREAD

**Issue by dpvreony** [reactiveui/splat#266]
I was going through MemoizingMRUCache in relation to https://github.com/reactiveui/ReactiveUI/issues/1315 needs some tests built around it and a sense check. I can see there were lock calls put in reactiveui around calling it in different scenarions. probably want to have a think about moving them down into this,

**Comment by glennawatson** [comment]
I tend to use a https://docs.microsoft.com/en-us/dotnet/api/system.threading.readerwriterlock?view=netframework-4.7.2 in these sorts of scenarios just due to the fact you generally have more reads.

**Comment by glennawatson** [comment]
Also in regards to https://github.com/reactiveui/ReactiveUI/issues/1315 the issue isn't so much the locks, it's more the fact the MRU releases the instances to dependency property based requests.
