### ISSUE TITLE
Splat failes on UWP release using Native tool chain

### ISSUE THREAD

**Issue by EmilAlipiev** [reactiveui/splat#281]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

When I am using the latest version of Akavache with Splat.

This also affects RxUI.

Everything works fine in debug once I try to run in release with native tool chain enabled, splat 6.1.7 produces several errors as below url. 

https://gist.githubusercontent.com/EmilAlipiev/9e14587b53173c02f292e0a18a0b3f5f/raw/0576b95823b8aa1ef2809a154ee81c3ee64853d0/gistfile1.txt

**Comment by glennawatson** [comment]
This has been slated to be investigated after v7 of splat has been released. This is in a couple weeks.

**Comment by glennawatson** [comment]
And thanks for reporting the issue @EmilAlipiev  -- even though you aren't directly using Splat this is probably the better location for the bug regardless.

**Comment by glennawatson** [comment]
This seems related to https://github.com/reactiveui/ReactiveUI/issues/1957 -- you  may want to upgrade as a work-around.

**Comment by EmilAlipiev** [comment]
6.2.3 is not available directly trough nuget. there was 6.2.2 but it had a bigger problem. Microsoft removed this version from nuget also. currently 6.1.9 is the best package to be used and uploaded on Store. at the moment i am using splat older version with 6.1.9 and it works fine for me

**Comment by glennawatson** [comment]
Well next release Splat will be going back to 6.1.9 anyway so this will be solved then.

**Comment by EmilAlipiev** [comment]
any news for this issue? latest akavache version is dependent on splat 6.1.7 and this issue blocks me to update akavache.

**Comment by glennawatson** [comment]
Hi there. We have other issues at the moment that backers from open collective have requested fixes for https://opencollective.com/reactiveui and those take priority. Hopefully soon though.

**Comment by glennawatson** [comment]
The aim is getting a release out soon with Splat time pending within the next week or so.

**Comment by glennawatson** [comment]
Fixed as part of the release coming today

**Comment by RLittlesII** [comment]
@EmilAlipiev Splat v7.0.1 has been released.  Please verify that this issue is resolved in that package?
