### ISSUE TITLE
Error Method doesn't exist: Splat.IDependencyResolver Splat.Locator.get_Current()'.'

### ISSUE THREAD

**Issue by Athuruga** [reactiveui/splat#292]
**Describe the bug**
I'm using Splat in my Project together with Reactive UI. I tried to upgrade from 6.1.7 to 8.0 dotnet3-preview5.
Before the upgrade my App was working, after the upgrade it fails with the error, that the Method doesn't exist:
Splat.IDependencyResolver Splat.Locator.get_Current()'.'

For example I have got a List of Accounts which I display in a Grid. I want to update the Grids Caption depending on the number of Items in the Script like:

this.WhenAny(x => x.QryAccountDetailList.Count,
                    (qryAccountDetailList) => new Tuple<int>
                    (qryAccountDetailList.Value))
    .Subscribe(values => { AccountCaption = GetCaption(values.Item1, GridCaptions.AccountGrid); });

With Version 6.1.7 this works like a charm, with 8.0 it stopped working.
After downgrading to the latest stable Version it is working again.

I'm using Splat because of the dependency to Reactive UI in an WinForms C# project.

Please let me know if this is a bug or what can I do to avoid this behavior.
Regards,
Athu

**Comment by glennawatson** [comment]
Yeah just stick with 6.1.7 at the moment. 

This one exists to allow a upcoming preview release of reactiveui for dotnet core 3 preview.
