### ISSUE TITLE
Housekeeping: improve test coverage

### ISSUE THREAD

**Issue by dpvreony** [reactiveui/splat#293]
Codecov shows current coverage at ~~19%~~ ~~47%~~ ~~58%~~ 70%

will take a look

**Comment by glennawatson** [comment]
This in part covers https://github.com/reactiveui/splat/issues/287

**Comment by glennawatson** [comment]
So we are aiming to get v7 out this week of Splat. So the remaining tasks are in the project. Do you want to include this for the v7 release @dpvreony ?

**Comment by dpvreony** [comment]
@glennawatson i'll follow up with this one rather than hold things upp

**Comment by glennawatson** [comment]
Part of this was addressed in #299

**Comment by dpvreony** [comment]
will close this for now as we passed 70% will have another bash once we close off some other items as they should naturally push it up anyway
