### ISSUE TITLE
For Splat Autofac use IComponentContext instead of IContainer in order to support ILifetimeScope

### ISSUE THREAD

**Issue by jalbertSyncroTech** [reactiveui/splat#302]
Autofac includes the concept of nested "lifetime" scopes where you can extend an existing container with a new child container that contains new registrations.

For our project, the registrations that would be relevant to ReactiveUI are part of a child lifetime scope and not the root container, but the existing UseAutofacDependencyResolver() can only take a root IContainer and not a child ILifetimeScope.

Both IContainer and ILifetimeScope have a common base interface IComponentContext which includes all of the Resolve() functions being used by Splat.Autofac AutofacDependencyResolver, so switching to using IComponentContext would allow ReactiveUI to resolve dependencies from the appropriate child lifetime scope.

Autofac > Docs > Controlling Scope and Lifetime
https://autofaccn.readthedocs.io/en/latest/lifetime/

ILifetimeScope Interface
https://autofac.org/apidoc/html/BA5D3489.htm

IComponentContext Interface
https://autofac.org/apidoc/html/D637B54C.htm

**Comment by RLittlesII** [comment]
@jalbertSyncroTech This sounds like an excellence suggestion!

For the interim.  All the `UseAutofacDependencyResolver()` is instantiate an `AutofacDepdndencyResolver`
https://github.com/reactiveui/splat/blob/2a1219c9562cb383e4fc8730d8152a6b8c2c7df8/src/Splat.Autofac/AutofacDependencyResolver.cs#L29

So my question would be, would you want the extension method to take the `IComponentContext` or the class itself?

**Comment by jalbertSyncroTech** [comment]
@RLittlesII I think it would need to be both.  IContainer also implements IComponentContext so it should be transparent to any existing consumers.

IContainer Interface
https://autofac.org/apidoc/html/F2A1E5DB.htm
