### ISSUE TITLE
Method not found: Splat.IDependencyResolver Splat.Locator.get_Current()

### ISSUE THREAD

**Issue by RwSgxx** [reactiveui/splat#310]
If this is a question please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/splat). - Would do, but I can't post because "code is not formatted correctly". Sorry it looks like I'm to stupid to understand code formatting on StackOverflow.

Method not found: Splat.IDependencyResolver Splat.Locator.get_Current()

I've just updated to the latest ReactiveUI and Xamarin Forms nugets and now I'm getting the error from the title.

ReactiveUI 9.11.3
ReactiveUI.Events.XamForms 9.11.3
ReactiveUI.XamForms 9.11.3
Xamarin.Forms 3.6.0.220655

And these are the code changes because of the changes in Splat:

Old code:

public class AutofacDependencyResolver : IMutableDependencyResolver {}
var resolver = new AutofacDependencyResolver(container);
Locator.Current = resolver;

New code:

public class AutofacDependencyResolver : IDependencyResolver {}
var resolver = new AutofacDependencyResolver(container);
Locator.SetLocator(resolver);

Is there something that I'm missing?

Thank you!

**Environment(please complete the following information):**
It doesn't really mater because I'm using it from Xamarin Forms.
 - OS: iOS
 - Version 12.1
 - Device: iPhone X

**Additional context**
Xamarin Forms

**Comment by glennawatson** [comment]
You definitely want to upgrade to reactiveui 9.12.1

**Comment by Dylan-IRISNDT** [comment]
I received a similar error on 9.12.1 that I haven’t been able to resolve when trying to initialize Akavache

**Comment by RLittlesII** [comment]
Seems there is an outstanding update for Akavache that needs to be released that targets Splat v7.  All these errors are because of the changes in Splat v7 and all the dependent libraries aren't there.

**Comment by glennawatson** [comment]
Akavache 6.5 has been released which supports Splat 7.x

Give it a go and let me know if you have any further issues.

https://github.com/reactiveui/Akavache/releases/tag/v6.5.1

**Comment by RwSgxx** [comment]
Update to the latest nugets (as of today) solved the problem.
Akavache 6.5.1
ReactiveUI 9.12.1

Thank you very much!

**Comment by EmilAlipiev** [comment]
there is breaking change seem liks Current became read only.
It was suggested to use akavache ondestroy like below but it seems that latest splat doesnt allow to initialize Current as it became readonly. does it make any difference? Do we still need the last line below?
```

protected override void OnDestroy()
        {
                 base.OnDestroy();
            Akavache.BlobCache.Shutdown().Wait();  // this calls the shutdown code

            Akavache.BlobCache.UserAccount = null; // clear out the static cached variables
            FieldInfo fi = typeof(Akavache.BlobCache).GetField("shutdownRequested", BindingFlags.Static | BindingFlags.NonPublic);
            fi.SetValue(null, false); // reset the private flag
       Splat.Locator.Current = new Splat.ModernDependencyResolver(); // create a new dependency resolver so akavache has to create new objects when the app is resurrected.

        }
```
