### ISSUE TITLE
Use IContainer instead of Container Splat.DryIOC

### ISSUE THREAD

**Issue by chrisgate** [reactiveui/splat#311]
Please note although we can't commit to any timeline, priority will be given to those who are [Contributors](https://github.com/reactiveui/splat#contribute ) to the project.

If this is a question please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/splat).

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Describe suggestions on how to achieve the feature**
A clear description to how to achieve the feature.

**Additional context**

**Comment by chrisgate** [comment]
There is no particular reason but i found that each time DryIoc team want to do anything to DryIoc they uses IContainer https://bitbucket.org/dadhi/dryioc/src/83c967d86332/Extensions/?at=default

**Comment by RLittlesII** [comment]
@chrisgate Thanks for submitting this issue.  Probably look into this and another issue with the Splat adapters soon.  Should be a minor change.
