### ISSUE TITLE
Method not found: Splat.IDependencyResolver Splat.Locator.get_Current() on Xamarin Forms after upgrading to version 7.2.1 from version 6.1.7

### ISSUE THREAD

**Issue by ClayeAAA** [reactiveui/splat#327]
**Describe the bug**
After upgrading my project to use reactiveui verson 9.15.1 (from 9.9.1) splat throws this missing method exception. 

**Environment(please complete the following information):**
 - Splat 7.2.1
 - ReactiveUI 9.15.1
 - Xamarin forms 3.6.0.344457
 - Device: Android

**Comment by glennawatson** [comment]
Hmm. Seems you have something that has a dependency on a old version of splat.

**Comment by ClayeAAA** [comment]
You are right, i hadn't noticed that my Bll project used splat for IOC. After updating my Bll project dependency, the missing method exception went away. Thanks for your insanely quick response.

**Comment by glennawatson** [comment]
No problem. The AOT compiler in xamarin Android is a bit finiky about that stuff
