### ISSUE TITLE
Using DryIoC with an ILogger

### ISSUE THREAD

**Issue by tombly** [reactiveui/splat#331]
Hello! 

We've been using Splat's logging and service location features for some time now and are tying to transition to DryIoC using the Splat.DryIoC nuget that replaces Splat's dependency resolver with a DryIoC container. 

We're having a problem where Splat's logging feature can't find the `ILogger` that we registered with the DryIoC container. For example:

```
	var c = new Container();
	c.Register<ILogger, MyLogger>();
	c.UseDryIocDependencyResolver();
	var d = Splat.Locator.Current.GetService<ILogger>();
	Splat.LogHost.Default.Debug("HELLO");
```

In the above code I would have expected that `d` would be assigned an instance of `MyLogger`, but instead it is of type `Splat.DebugLogger`. In addition (and consequently), the call to `Debug()` is routed to the `DebugLogger` instead of to `MyLogger`.

Is it possible to use both Splat.DryIoC and Splat's logging feature?

Thanks!
-Tom B.

**Comment by glennawatson** [comment]
I have a suspicion that the splat logger gets registered on the call to UseDryIocDependencyResolver. If you move the register to after that call it may be a workaround to your issue until the bug gets fixed.

**Comment by tombly** [comment]
Thanks for the quick reply. I tried your suggestion but unfortunately got the same results:

```
	var c = new Container();
	c.UseDryIocDependencyResolver();
	c.Register<ILogger, MyLogger>();
	var d = Splat.Locator.Current.GetService<ILogger>();
	Splat.LogHost.Default.Debug("HELLO");
```
But I found that if I unregister and re-register then it uses the correct ILogger:

```
	var c = new Container();
	c.UseDryIocDependencyResolver();
	c.Unregister<ILogger>();
	c.Register<ILogger, MyLogger>();
	var d = Splat.Locator.Current.GetService<ILogger>();
	Splat.LogHost.Default.Debug("HELLO");
```

Thanks again for the help!

-Tom B.

**Comment by dpvreony** [comment]
I've added logic to check if registration took place prior to hooking the container up to splat. that resolves your call to set up logging prior to splat, as for the latter case as you're working with the DryIoC container directly, it's a nuance of the container.

for a 1 liner in your workaround you can use

`                _container.Register<ILogger, DebugLogger>(ifAlreadyRegistered: IfAlreadyRegistered.Replace);`

**Comment by tombly** [comment]
Thanks for the follow-up!
