### ISSUE TITLE
[BUG] Requires Investigation: Bitmap loader on netcore and net462

### ISSUE THREAD

**Issue by dpvreony** [reactiveui/splat#338]
**Describe the bug**
When I was sense checking the Bitmap loader for android and increasing the test coverage I _think_ I spotted a gap in the .net core\wpf availability of a platform bitmap loader. This is a reminder as it needs to be checked.

**Steps To Reproduce**
The unit test for the platform loader was restricted to android, so remove the #if macro. need to assess and discuss.

**Expected behavior**
Platform bitmap loader works as expected on each platform.

**Comment by glennawatson** [comment]
WPF .net core is still in previous and is on the preview/8.0 branch. https://github.com/reactiveui/splat/blob/preview/8.0-dotnet/src/Splat/Platforms/netcoreapp3/Bitmaps/PlatformBitmapLoader.cs is the bitmap loader.

**Comment by dpvreony** [comment]
closing. not an issue. thing I spotted it specific to android and the reflection for resources.
