### ISSUE TITLE
feature: Add Microsoft.Extensions.DependencyInjection adapter

### ISSUE THREAD

**Issue by RLittlesII** [reactiveui/splat#362]
Add a Microsoft.Extensions.DependencyInjection package

Relates To: #233

**Comment by weitzhandler** [comment]
Can I PR?

**Comment by glennawatson** [comment]
See Rodney message on Slack

**Comment by weitzhandler** [comment]
LOL, I just saw it so I deleted my message. Gonna delete this one too to keep the clutter out

**Comment by weitzhandler** [comment]
There are few things different in Msft DI, in my own project I implemented it the way I found as right but if I'm to PR, I better consult with you guys.

### A resolver isn't mutable
In Msft DI, there is no mutable-resolver. There is either configurator or resolver, once the provider is built, it's locked up and you can no longer inject new services.

What I've done is added an intermediate interface `IMicrosoftDependencyResolver` that provides an `UpdateServiceProvider` method, that allows plugging in the container once it's ready by the service host etc. if not plugged in, the resolver builds the provider itself if requested.

### No registration with string contracts
Msft doesn't provide `contract` or keying of services.

Should we completely ignore the parameter, raise an exception if it's provided?
Otherwise maybe inherit from `ModernDependencyResolver` registering and resolving internally using MS DI?

**Comment by glennawatson** [comment]
David has got around point 1 by rebuilding the locator instance with other resolvers. 

Second point you have scoped operations in ms di extensions which are attempting to do the same thing as contracts.

**Comment by weitzhandler** [comment]
> rebuilding the locator instance with other resolvers.

What do you mean? In Splat, during the configure container stage there are calls to the provider (for logging). MS doesn't support this. How do you notify the resolver that its provider is different?

**Comment by glennawatson** [comment]
See https://github.com/reactiveui/splat/blob/24b9fea73927e8586e02edbfb77bc61b9229f6ca/src/Splat.Autofac/AutofacDependencyResolver.cs#L328

Essentially unregister on autofac will scan through all items registered. Create a fresh container. Add back all services but the one removed.

**Comment by glennawatson** [comment]
If that's not feasible then exception is fine

**Comment by weitzhandler** [comment]
I'm not familiar with AutoFac, but is it also that there is a 'build' point that the service collection gets locked up?

**Comment by glennawatson** [comment]
Yep most do that. Our general idea it should stop being mutable when you run the extension method to register it with splat

**Comment by weitzhandler** [comment]
You can't do that, because while splat registers its services, it also tries to consume some of them (for example loggers).

**Comment by glennawatson** [comment]
Every di we offer btw has a extension method to set it as the di engine inside splat.

**Comment by glennawatson** [comment]
So until that point it doesn't attempt to consume it.

**Comment by weitzhandler** [comment]
Wouldn't it be better to dedicate a special interface that provides this 'override'?

https://github.com/reactiveui/splat/compare/master...weitzhandler:master

**Comment by glennawatson** [comment]
Nope. This keeps it consistent

**Comment by weitzhandler** [comment]
Oh, [I see now](https://github.com/reactiveui/splat/blob/master/src/Splat.Autofac/SplatAutofacExtensions.cs). It's the same ex. method over the container. Looks good and less verbose than an interface indeed.

**Comment by glennawatson** [comment]
So yeah. The idea is you do all your registration either in the splat override or your native di, use the extension method and after that point it's immutable

**Comment by weitzhandler** [comment]
https://github.com/reactiveui/splat/blob/305c589a9ef84ba2021e1e84227f27664b6936e8/src/Splat.Autofac/AutofacDependencyResolver.cs#L88

How to implement `Register` since MS DI doesn't offer any `Update` method.

**Comment by glennawatson** [comment]
Add () is a similar mechanism

**Comment by dpvreony** [comment]
autofac's builder.update method is actually obsolete, so the "unregister" rebuild logic will probably have to to be used by add at some point

**Comment by RLittlesII** [comment]
That was the problem I ran into with Simple Injector.  The container is only built once.  I thought I found away around it, but I let the branch go stale for other priorities.

I thought you had a working implementation?

This should be no more difficult than hooking your working solution into the same structure as the other DI Adapters already implemented.  All the code is generally the same.

There is also some work going on that may change how some of the adapters are implemented.  So you might want to be aware to reduce additional efforts.

I'll dig up that branch and see if it can provide a baseline.

**Comment by glennawatson** [comment]
I think all these containers will be way easier if we just make it immutable with the extension method.

**Comment by weitzhandler** [comment]
Does it look any better now?
https://github.com/reactiveui/splat/compare/master...weitzhandler:master

**Comment by RLittlesII** [comment]
One minor observation, it's usually better to work on a branch off master for pull requests.

Looks closer to what I was imagining.

**Comment by weitzhandler** [comment]
> One minor observation, it's usually better to work on a branch off master for pull requests.

Will remember that in the future.

> Looks closer to what I was imagining.

So can I focus on making some tests?

**Comment by dpvreony** [comment]
just a heads up. I was looking at your branch. your unit test project csproj can be simplified. the directoy.build.props detects test projects and includes xunit etc. also the main unit test package uses msbuild.extras - I would just compare one of the others and tweak :)

also I've included a base unit test class for some of the repeatable tests.
