### ISSUE TITLE
feature: rename all external DI mixins to a single name

### ISSUE THREAD

**Issue by weitzhandler** [reactiveui/splat#379]
There is the `UseMicrosoftDependencyResolver`, `UseAutofacDependencyResolver` and the others, why not have just `UseDependencyResolver(overloads for all DI providers)`?

Because really we're calling the ex. method on the external DI container anyway which we want to dress up with Splat, so we don't need to have the names different.

**Comment by glennawatson** [comment]
It's self documenting to the user what di engine they are using. Don't want all the same name.

**Comment by weitzhandler** [comment]
Thanks

**Comment by glennawatson** [comment]
Also not dissimilar to the Microsoft extensions approach. Eg with all their extension methods.
