### ISSUE TITLE
[BUG] ReportAbuse The package contains malicious code http://f.cl.ly/items/1307401C3x2g3F2p2Z36/Logo.png

### ISSUE THREAD

**Issue by wzuqui** [reactiveui/splat#388]
ReportAbuse
https://www.nuget.org/packages/Splat/8.2.4

<?xml version="1.0" encoding="utf-8" ?>
<ESET>
  <LOG>
    <RECORD>
      <COLUMN NAME="Hora">15/08/2019 09:52:47</COLUMN>
      <COLUMN NAME="URL">http://f.cl.ly/items/1307401C3x2g3F2p2Z36/Logo.png</COLUMN>
      <COLUMN NAME="Status">Bloqueado pela lista de proibições de antiphishing</COLUMN>
      <COLUMN NAME="Aplicativo">C:\Program Files (x86)\Google\Chrome\Application\chrome.exe</COLUMN>
      <COLUMN NAME="Usuário">...</COLUMN>
      <COLUMN NAME="Endereço de IP">52.216.82.8</COLUMN>
      <COLUMN NAME="SHA1">1CCB6DC512FB00DBB3168CA0449620EA306DCC00</COLUMN>
    </RECORD>
 </LOG>
</ESET>

**Comment by glennawatson** [comment]
This issue does not follow our template. Closing.
