### ISSUE TITLE
[BUG] Nuget loads Icon image from problematic domain

### ISSUE THREAD

**Issue by gitter-me** [reactiveui/splat#391]
**Describtion**
The nuget package uses a icon which is loaded from a domain that is flagged by our company antivirus (ESET Endpoint Antivirus) as harmful domain: http://f.cl.ly/items/1307401C3x2g3F2p2Z36/Logo.png

**Steps To Reproduce**
1. Open the nuget manager in Visual Studio or Rider in a project with splat
2. The AV warning popup appears, when the logo should be fetched

**Expected behavior**
A unproblematic domain should be used for hosting the icon

**Environment(please complete the following information):**
 - OS: Win 10 
 - Version 1094 

**Additional context**
Alternatively the AV-Vendors could be informed to whitelist the domain

**Comment by RLittlesII** [comment]
@gitter-me Thank you for this issue.  We actually started work last week to centralize all of the logo's.  This is actually currently in progress.  I will track that status here.

**Comment by glennawatson** [comment]
This was updated as part of the 8.3.1 release of Splat.
