### ISSUE TITLE
[BUG] 9.22.1 crashes MSBUILD on netcoreapp3.0 preview8

### ISSUE THREAD

**Issue by vladhorby** [reactiveui/splat#396]
**Describe the bug**

After updating from 9.21.1 to 9.22.1 for a netcoreapp3.0 preview 8 project, MSBUILD crashes on build (Visual Studio 2019).

**Steps To Reproduce**
1. Create an empty ASP.NET CORE 3.0 project.
2. Add a nuget reference to ReactiveUI 9.21.1
3. Build - All OK.
4. Update nuget reference to ReactiveUI 9.22.1
5. Build - Getting a MSBUILD error.

.csproj file:
`<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
	<ItemGroup>
    <PackageReference Include="ReactiveUI" Version="9.22.1">
		</PackageReference>
  </ItemGroup>
</Project>`

**Expected behavior**

Project should build successfully.

**Error messages**

Getting a modal dialog error message:
MSBuild.exe - "A new guard page for the stack cannot be created".

The output message:
`------ Rebuild All started: Project: Web, Configuration: Debug Any CPU ------
You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview`
`MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "C:\Users\[USERNAME]\AppData\Local\Temp\" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.`
`========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========`

MSBuild_*.failure.txt contains:

> UNHANDLED EXCEPTIONS FROM PROCESS 15672:
=====================
2019-08-28 15:52:22
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
===================

**Environment**

- OS:      Windows
- Version   10 Pro
- Net CORE: 3.0 Preview 8
- Visual Studio 2019 16.3.0 Preview 2 (tried 16.2.3 too)

**Additional context**

Workaround: revert to 9.21.1

**Comment by glennawatson** [comment]
I will most likely introduce a splat.wpf and splat.winforms package now

**Comment by glennawatson** [comment]
Thanks for the decent investigation into the issue. It makes providing a solution much easier.

**Comment by vladhorby** [comment]
I'm using it in a asp net core 3.0 project - it's a netcoreapp3.0, but, of course, has no dependencies on windows - so I guess that's why msbuild crashes.
I've been experimenting with using ReactiveUI with Blazor and it has been working pretty nicely (until this bump).
Thank you for all the great work!

**Comment by glennawatson** [comment]
This will be solved as part of the 9.0 release of Splat.
