### ISSUE TITLE
[BUG] 'IBitmap' does not contain a definition for 'ToNative'...

### ISSUE THREAD

**Issue by jctlp** [reactiveui/splat#427]
Question asked on [StackOverflow](https://stackoverflow.com/questions/58840777/visual-studio-cant-find-extension-methods-splat-bitmapmixins-fromnative-and-s)

**Describe the bug**
When attempting to call IBitmap.ToNative() or Bitmap.FromNative() we receive compiler errors despite having both Splat and Splat.Drawing referenced in both the .NET Standard project and the Android project. 
Further troubleshooting indicates that Visual Studio may not be attempting to bind the Android versions of the libraries, see SO question for full details.

**Steps To Reproduce**
1. Create a new Xamarin solution selecting .NET Standard for the code sharing project and Android for the platform
2. Using NuGet reference Splat and Splat.Drawing in both projects.
3. In the Android project, create a class with a method that calls the .ToNative() and .FromNative() methods
4. See errors:
'IBitmap' does not contain a definition for 'ToNative' and no accessible extension method 'ToNative' accepting a first argument of type 'IBitmap' could be found (are you missing a using directive or an assembly reference?)
'Bitmap' does not contain a definition for 'FromNative' and no accessible extension method 'FromNative' accepting a first argument of type 'Bitmap' could be found (are you missing a using directive or an assembly reference?)

An example project can be found on [Github](https://github.com/jctlp/SplatBitmap)

**Expected behavior**
No compiler error

**Environment(please complete the following information):**
 - OS: Android
 - Target Framework: 8.1
 - Device: N/A

**Comment by dpvreony** [comment]
The project is targeting Android 8.1 which means Xamarin Forms targets the Splat netstandard2.0 dll. Changing to Android 9.0 fixes the issue.

Closing in line with https://reactiveui.net/docs/getting-started/minimum-versions
