### ISSUE TITLE
[BUG] Serilog Structured logging not working

### ISSUE THREAD

**Issue by rgomez90** [reactiveui/splat#439]
**Describe the bug**
When using `Splat.Serilog` a `FormatException` is thrown when trying to use structured logging syntax.

For example: `this.Log().Debug("{@item}",item)` will raise the exception. The issue is appears in `Debug` as well as in all other levels.

**Steps To Reproduce**
Run this sample:
```cs
void Main()
{
    Log.Logger = new LoggerConfiguration().MinimumLevel.Debug()
		.WriteTo.Async(configuration => configuration.Console())
                .Enrich.FromLogContext()
                .CreateLogger();

    var logger = new SerilogFullLogger(Log.Logger) { Level = LogLevel.Error };
    Locator.CurrentMutable.RegisterConstant(logger, typeof(Splat.ILogger));

    var testObject = new TestObject();
    testObject.DoSomething();
}

public class TestObject : ReactiveObject
{
    public void DoSomething()
    {
        this.Log().Info("{@item}", new Item(1, "Test"));
    }
}

public class Item
{
    public Item(int number, string name)
    {
        Number = number;
        Name = name;
    }
    public int Number { get; set; }
    public string Name { get; set; }
}
```
It appears to have something to do with `{}` since `this.Log().Debug("{}",item)` raises the exception too, but `this.Log().Debug("@item",item)` works and prints `@item` in the logs.

**Expected behavior**
No exception should be raised. Structured logging should be possible.

**Environment(please complete the following information):**
 - OS: Win 10 Pro
 - Version: ReactiveUI 10.5.31

**Comment by glennawatson** [comment]
Use the extension methods found in https://github.com/reactiveui/splat/blob/6ab27ebc6739e8dd778223b623ee9dca99a625d1/src/Splat.Serilog/MutableDependencyResolverExtensions.cs#L33

**Comment by glennawatson** [comment]
I think using the extension methods and it using the func log manager should solve your issue. Shout back if it doesn't.
