### ISSUE TITLE
Splat's DebugLogger writes nothing

### ISSUE THREAD

**Issue by moswald** [reactiveui/splat#46]
I suspect it's because the library was built for release, and Debug.WriteLine is culled from the resulting binary.

**Comment by ghuntley** [comment]
See also #123 and #58

**Comment by Belorus** [comment]
Please have a look at XLog - https://github.com/Belorus/XLog/wiki if you care about logging performance

**Comment by ghuntley** [comment]
@Belorus would you be interested in rewriting our implementation instead of having to maintain xlog?

**Comment by Belorus** [comment]
@ghuntley, sure, i can try. Would be pleasure if it will save few milliseconds for more people. I'll get in touch with PR in a week with results

**Comment by ghuntley** [comment]
@Belorus just make sure you open a discussion / WIP with your changes early before storming ahead.

**Comment by cabauman** [comment]
Copying that snippet from @moswald's comment worked for me (adding our own debugger). Wasn't getting anything in the output window, otherwise. Thanks.

**Comment by ghuntley** [comment]
This knowledge has been documented over at https://reactiveui.net/docs/guidelines/debugging/enable-framework-logging 🚢

**Comment by cabauman** [comment]
Thanks @ghuntley but I've already tried that section of the documentation before. That page, among others, are blank.
![img_0298](https://user-images.githubusercontent.com/6819362/30789232-0d4b56d2-a1df-11e7-947b-8efa83b0dcae.PNG)
![img_0299](https://user-images.githubusercontent.com/6819362/30789231-0d4b40d4-a1df-11e7-9d1c-ae016e424da1.PNG)
