### ISSUE TITLE
[BUG] PlatformBitmapLoader throws System.NotSupportedException

### ISSUE THREAD

**Issue by takacsalbert** [reactiveui/splat#478]
Description
On UWP the PlatformBitmapLoader.Load() method throws System.NotSupportedException saying 
"Cannot use the specified Stream as a Windows Runtime IRandomAccessStream because this Stream does not support seeking."
Here is the line that throws error:
LINE 28: using (var randomAccessStream = sourceStream.AsRandomAccessStream())

Steps To Reproduce
Use BitmapLoader.Current.Load() method in a UWP app.

Expected behavior
BitmapLoader.Current.Load() method doesn't throw an exception.

Versions
Splat version 9.3.11
Splat.Drawing version 9.3.11

Environment
 - OS: Windows 10 (Version 1909, 18363.720)
 - UWP Target and Minimum Version: 10.0, Build 16299
 - Visual Studio 2019 16.4.5

Tests
It seems that the unit test is missing for UWP, please add it to the project.

**Comment by takacsalbert** [comment]
Started to dig into this and finally came to a solution that works fine. I hope you find it useful.
I found the answer here: https://forums.xamarin.com/discussion/16500/bitmap-decode-byte-array-skia-decoder-returns-false

And the solution:
var buffer = imageArray.Concat(new byte[] { (byte)0xFF, (byte)0xD9 }).ToArray();
bitmap = await BitmapFactory.DecodeByteArrayAsync(buffer, 0, buffer.Length);

This works for jpg and png images.

**Comment by glennawatson** [comment]
Is this one fixed now @dpvreony ?

**Comment by dpvreony** [comment]
not sure will check this and #519
