### ISSUE TITLE
[BUG] Using NInject and NLog extensions prevent resolution of ILogManager

### ISSUE THREAD

**Issue by MarkARussell** [reactiveui/splat#553]
**Describe the bug**
After initializing NInject and NLog, the ILogManager service can't be resolved (always null)

**Steps To Reproduce**
1. Initialize NInject:
```
var kernel = new StandardKernel();  
kernel.UseNinjectDependencyResolver();
```
2. Initialize NLog
`Locator.Current.UseNLogWithWrappingFullLogger();`
3. Attempt to resolve ILogManager
`ILogManager lm = Locator.Current.GetService<ILogManager>();`
4. See that the ILogManager is null

**Expected behavior**
The ILogManager should not be null

**Environment(please complete the following information):**
 - Windows 10 2004
 - C# .NET Core 3.1
 - Tested in WPF app and via .NET Core Unit Test on my desktop machine

**My Analysis of what is happening**
Root cause: two instances of ILogManager are getting registered when there should probably only be one and the service resolver can't figure out which one to select, and thus returns null.

Logic Chain:
1. In the InternalLocator class constructor, a callback is registered for when the resolver changes that will cause a reinitialization of Splat when the NInject resolver replaces the default.  This in turn will cause the registration of a default ILogManager (among others) with the NInject container.
2. The UseNLogWithWrappingFullLogger() extension method calls RegisterConstant() with an ILogManager implementation specifically for NLog.  Due to the current implementation of the NinjectDependencyResolver class, this will result in a SECOND registration of an ILogManager (i.e. the NInject container now has two separate bindings for ILogManager)
3. When attempting to resolve the ILogManager, the implementation of NinjectDependencyResolver calls TryGet(Type) on the NInject kernel.  The implementation of this function (inside ResolutionExtensions in the NInject source code) uses the function SingleOrDefault() to attempt to get the one and only instance of the type from an enumeration of bound instances.  In this case, because more than one registration exists an exception gets thrown that the TryGet function handles by returning a null object.

Problem may exist with other DI containers as well, though I have not tested.
Work-around: Before calling UseNLogWithWrappingFullLogger(), forcibly unbind the ILogManager from the NInject kernal (to ensure one and only ILogManager instance)

**Additional context**
Project with Unit Test demonstrating the problem
[Splat_NInject_NLog_Issue.zip](https://github.com/reactiveui/splat/files/5011108/Splat_NInject_NLog_Issue.zip)

The unit test itself (so you don't have to open the zip)
```
        [TestMethod]
        public void ILogManager_Resolvable()
        {
            // Setup NInject as our IoC container
            var kernel = new StandardKernel();
            kernel.UseNinjectDependencyResolver(); // Register the kernel w/ Splat

            // Setup NLog for Logging (doesn't matter if I actually configure NLog or not)
            Locator.CurrentMutable.UseNLogWithWrappingFullLogger();

            // Get the ILogManager instance (this should succeed, but fails in current code)
            ILogManager lm = Locator.Current.GetService<ILogManager>();
            Assert.IsNotNull(lm, "ILogManager could not be resolved");
        }
```

**Comment by glennawatson** [comment]
Most other di engines if they have multiple registrations we just get the latest one. Might have to do something with ninject.

**Comment by MarkARussell** [comment]
One possible solution would be to tweak the NinjectDependencyResolver such that the GetService() call uses NInject's GetAll() function and returns the last element from the result.  That would most closely match what you say the other engines do.  There is some slight risk of this breaking in the future as it appears to rely on the undocumented assumption that last == latest, but at least with their current implementation it appears the last element will be the latest.

**Comment by dpvreony** [comment]
investigating. need to be careful not to break #483 which is why we went to TryGet

**Comment by MarkARussell** [comment]
Possible paranoid implementation that leaves the TryGet intact, and only falls back to GetAll if it fails:
```
public virtual object GetService(Type serviceType, string contract = null) {
	object resolved = string.IsNullOrEmpty(contract)
					? _kernel.TryGet(serviceType)
					: _kernel.TryGet(serviceType, contract);
	if (resolved == null) {
		// If TryGet() above failed, then either there were no registration -OR- there were multiple
		// registrations. Attempt to get the last (most recent) registration for the latter case.
		var allResolved = string.IsNullOrEmpty(contract)
						? _kernel.GetAll(serviceType)
						: _kernel.GetAll(serviceType, contract);
		resolved = allResolved?.LastOrDefault();
	}
	return resolved;
}
```
I'm making the assumption here that GetAll() doesn't throw, but given there is no TryGetAll() I'm pretty sure it doesn't.

**Comment by dpvreony** [comment]
to update splat.ninject had a bunch of missing unit tests from standard tests. 6 failing.

**Comment by dpvreony** [comment]
down to 1 failing test
