### ISSUE TITLE
[BUG] Usage of Autofac as resolver never load assembly modules in UWP

### ISSUE THREAD

**Issue by ushenkodmitry** [reactiveui/splat#591]
Please note although we can't commit to any timeline, priority will be given to those who are [Contributors](https://github.com/reactiveui/splat#contribute ) to the project.

If this is a question please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/splat).

**Describe the bug**
The code below doesn't load any of modules defined within executing assembly.
```
        protected override void OnLaunched(LaunchActivatedEventArgs e)
        {
            var assembly = Assembly.GetExecutingAssembly();

            var builder = new ContainerBuilder();
            builder.RegisterAssemblyModules(assembly);
            builder.UseAutofacDependencyResolver();
            ...
        }
```
Seems like a regression as the same exactly code was working about a week ago.

**Steps To Reproduce**
1. Create new UWP app
2. Add the code above
3. Define a module and add a breakpoint in the Load method
4. Run
5. See that breakpoint is not hitting

**Expected behavior**
Breakpoint hitting.

**Environment(please complete the following information):**
 - OS: Windows 10
 - Device: PC

**Additional context**
    Splat.Autofac 9.5.49

**Comment by glennawatson** [comment]
Take a look here

https://github.com/reactiveui/splat/blob/main/src/Splat.Autofac/README.md

There's one or two extra steps

**Comment by ushenkodmitry** [comment]
Thank you. But it didn't help. Here is my code:
```
            var assembly = Assembly.GetExecutingAssembly();

            var builder = new ContainerBuilder();
            builder.RegisterType<MainViewModel>().AsSelf().As<IScreen>().SingleInstance();
            builder.RegisterAssemblyModules(assembly);
            var resolver = builder.UseAutofacDependencyResolver();
            resolver.InitializeReactiveUI();
            builder.RegisterInstance(resolver);
```
No module loaded, MainViewModel can not be resolved via Locator.Current.GetService<MainViewModel>(). The method returns null;

**Comment by ushenkodmitry** [comment]
Fixed on my side, sorry
```
            var assembly = Assembly.GetExecutingAssembly();

            var builder = new ContainerBuilder();
            builder.RegisterAssemblyModules(assembly);
            var resolver = builder.UseAutofacDependencyResolver();
            resolver.InitializeReactiveUI();
            builder.RegisterInstance(resolver);
            resolver.SetLifetimeScope(builder.Build());
```
