### ISSUE TITLE
net5 windows specific version targetting?

### ISSUE THREAD

**Issue by dpvreony** [reactiveui/splat#635]
we're currently targeting net5-windows based on @clairernovotny comments on twitter do we want to align to the UAP version and use net5-windows10.0.16299 ?

https://twitter.com/clairernovotny/status/1329472367781945344

**Comment by glennawatson** [comment]
I wasn't using it for uap funnily but for wpf winforms .

**Comment by dpvreony** [comment]
closing as not really required
