### ISSUE TITLE
[BUG] Locator with  inherited type

### ISSUE THREAD

**Issue by RomanSoloweow** [reactiveui/splat#751]
Is it possible to use a locator with inherited types? Is it possible to somehow circumvent the limitation and is it not worthwhile to provide an option for such cases?

```C#
interface A
{
}

interface B:A
{
}

Locator.CurrentMutable.RegisterConstant(B, myId); //registered

var b = Locator.Current.GetService<B>(myId); // ok
var a = Locator.Current.GetService<A>(myId); //null
```

**Comment by glennawatson** [comment]
You can make your own I guess. The goal of our container is minimal reflection. We just do type matching

**Comment by ChrisPulman** [comment]
@RomanSoloweow I tested the following:
