### ISSUE TITLE
desiredWidth and desiredHeight

### ISSUE THREAD

**Issue by dylanvdmerwe** [reactiveui/splat#78]
I don't think the BitmapLoader Load method actually resizes images in iPhone.

In iPhone I'm looking through the source code of Bitmaps.cs for Cocoa and there is no code using the two size variables.

**Comment by halfnelson** [comment]
The android loader doesn't resize the image either, it is passing the desiredWidth and desiredHeight variables to the outHeight and outWidth parameters of the opts bag, these capture the size of the image, not modify.
