### ISSUE TITLE
[BUG] Potential problem with branch information in Contributing document

### ISSUE THREAD

**Issue by gep13** [reactiveui/splat#780]
**Describe the bug**

The contributing guidelines suggest that a feature branch should be taken from, and a PR submitted to, the `develop` branch of this repository.  Looking at the active branches, there is no `develop` branch, but rather a `main` branch. 

Should the guidelines be updated to recommend/suggest that the `main` branch is used for PR's?  Or is there another branch that you would like folks to target?

**Steps To Reproduce**
Provide the steps to reproduce the behavior:
1. Navigate to the `Submitting a Pull Request` section of the Contributing Guide
  * https://github.com/reactiveui/splat/blob/main/CONTRIBUTING.md#submitting-a-pull-request
2. See that it mentions `develop` branch, rather than `main`

**Expected behavior**

Instructions on which branch to use should reflect that actual branches of the repository

**Screenshots**

![2021-09-30_07-15-10](https://user-images.githubusercontent.com/1271146/135397562-c5b9368b-f1a3-40fb-bbeb-892ee28d0492.png)

**Environment(please complete the following information):**

Not applicable as this is a documentation issue

**Additional context**

Not applicable

**Comment by glennawatson** [comment]
Should be definitely updated to main. Thanks for pointing out the documentation issue.
