### ISSUE TITLE
Strong names for dlls

### ISSUE THREAD

**Issue by tapika** [reactiveui/splat#785]
It's so that if main application is using strong names - it requires from all packages to have strong names as well.

This will manifest as run-time error, when you try to launch the application:

```
Could not load file or assembly 'Splat.Drawing, Version=13.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
```

Would it be possible to add assembly signing - at least for `Splat.Drawing`, if not any other packages ?

**Comment by tapika** [comment]
Using strongnamer also results in failure, created separate ticket on this issue:

https://github.com/dsplaisted/strongnamer/issues/59

**Comment by glennawatson** [comment]
This discussion has come up a few times. Too many disadvantages to signing. Mainly it forces binding redirects where it doesn't exist before. Also in net core and above it has becoming increasingly unnecessary
