### ISSUE TITLE
[BUG] Project targeting net5.0 won't build with Splat.Drawing installed 

### ISSUE THREAD

**Issue by n-ski** [reactiveui/splat#809]
**Describe the bug**
Building a .NET 5 project with Splat.Drawing installed fails with the following message:
> C:\Program Files\dotnet\sdk\5.0.206\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(362,5): error NETSDK1136: The target platform must be set to Windows (usually by including '-windows' in the TargetFramework property) when using Windows Forms or WPF, or referencing projects or packages that do so.

**Steps To Reproduce**
I have this C# cross-platform library project file.

```csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Splat.Drawing" Version="13.*" />
  </ItemGroup>
</Project>
```

Running `dotnet build` yields the error described above. Project will build successfully if TFM is set to `netstandard2.1`.

**Expected behavior**
Project should build successfully when targeting .NET 5.

**Environment:**
- OS: Windows 10 1809 x64
- .NET SDK: 5.0.206

**Additional context**
Looking at _project.assests.json_ it seems like `netcoreapp3.1` version of Splat.Drawing is being referenced since there isn't a compatible `net5.0` target:
```json
  "targets": {
    "net5.0": {
      "Splat/13.1.30": {
        "type": "package",
        "compile": {
          "lib/net5.0/Splat.dll": {}
        },
        "runtime": {
          "lib/net5.0/Splat.dll": {}
        }
      },
      "Splat.Drawing/13.1.30": {
        "type": "package",
        "dependencies": {
          "Splat": "13.1.30"
        },
        "compile": {
          "lib/netcoreapp3.1/Splat.Drawing.dll": {}
        },
        "runtime": {
          "lib/netcoreapp3.1/Splat.Drawing.dll": {}
        },
        "frameworkReferences": [
          "Microsoft.WindowsDesktop.App"
        ]
      }
    }
  },
```

**Comment by dpvreony** [comment]
The error is indicating to use

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Splat.Drawing" Version="13.*" />
  </ItemGroup>
</Project>
```

Even targeting netstandard2.1 should be giving you the build warning NU1701 about how it is resolving the package.

Splat Drawing contains platform specific logic. For net5 that is only available in PresentationFramework via net5.0-windows

JpegBitmapEncoder 

Your other option is use TargetFrameworks and pick the ones you need
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
<TargetFrameworks>MonoAndroid90;Xamarin.iOS10;Xamarin.Mac20;Xamarin.TVOS10;Xamarin.WatchOS10;tizen40;netstandard2.0;net6.0-android;net6.0-ios;net6.0-tvos;net6.0-macos</TargetFrameworks>
    <TargetFrameworks Condition=" '$(OS)' == 'Windows_NT' ">$(TargetFrameworks);net461;net472;uap10.0.16299;netcoreapp3.1;net5.0-windows;net6.0-windows</TargetFrameworks>  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Splat.Drawing" Version="13.*" />
  </ItemGroup>
</Project>
```

if i'm missing something in what you're trying to achieve please say.

@glennawatson is the actual issue that we need to remove netstandard because it's a platform specific dll?

**Comment by glennawatson** [comment]
netstandard should be valid for WASM based projects. Same for net5/6
