### ISSUE TITLE
Load symbols/source up to standard locations for debugging

### ISSUE THREAD

**Issue by gordonwatts** [reactiveui/splat#88]
I can't step into splat - I can with Reactive UI, etc., and when I tell it to load symbols it claims "splat.pdb" couldn't be found.

**Comment by paulcbetts** [comment]
As I recall, SymbolSource barfs on our NuPkg files with a weird exception and a 500, but I'll look again the next time I do a release

**Comment by gordonwatts** [comment]
Your ReactiveUI stuff seems to work - so the problem is unique to Splat, perhaps? I had this problem a while back, and I used a plug-in from the symbolsource folks to help sort it out... I think I got instructions on what to do from here: http://www.symbolsource.org/Public/Wiki/Publishing - hopefully that is helpful.

Also, on twitter, the symbolsource people were very helpful, even looking at one of the internal logs for me to help guide me in getting the package fixed. In general the error messages weren't helpful. :-)
