### ISSUE TITLE
Update Splat.Autofac README

### ISSUE THREAD

**Issue by johnmwilson82** [reactiveui/splat#882]
Hello, I just ran into this bug: https://github.com/AvaloniaUI/Avalonia/issues/5298

In my case I was getting `System.InvalidOperationException:“Call from invalid thread”` when I was firing a ReactiveCommand on a VM from a view.

The proposed solution, adding the following lines:

```
RxApp.MainThreadScheduler = AvaloniaScheduler.Instance;
Locator.CurrentMutable.RegisterConstant(new AvaloniaActivationForViewFetcher(), typeof(IActivationForViewFetcher));
Locator.CurrentMutable.RegisterConstant(new AutoDataTemplateBindingHook(), typeof(IPropertyBindingHook));
```

under `autofacResolver.InitializeReactiveUI()` worked for me (after an afternoon of confusion).

Any possibility of getting the [Splat.Autofac README](https://github.com/reactiveui/splat/blob/main/src/Splat.Autofac/README.md) updated to add the above lines?

**Comment by glennawatson** [comment]
Probably worth getting it added to the avalonia docs if you can and then we will link to their docs. 

Avalonia do their own rxui plugin so we tend to link to their documentation to keep it all in one place on their side.
