### ISSUE TITLE
[BUG] DryIoc resolves Views upon registration

### ISSUE THREAD

**Issue by RejectKid** [reactiveui/splat#889]
Please note although we can't commit to any timeline, priority will be given to those who are [Contributors](https://github.com/reactiveui/splat#contribute ) to the project.

If this is a question please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/splat).

**Describe the bug**
When using the UseDryIocDependencyResolver and View Location, the views get resolved immediately before actually having VMs.  When using the default Splat locator this isnt an issue

**Steps To Reproduce**
Provide the steps to reproduce the behavior:
1) setup typical RxUI app
2) use UseDryIocDependencyResolver instead of splat
3) utilizing View Location notice the Views wont be made as the pipe is dead before the VMs are created

**Expected behavior**
Shouldnt resolve the Views immediately and only when the VMs come through (on a observable collection for example).  AKA should act like splat is working :-)

**Screenshots**

**Environment(please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by glennawatson** [comment]
Try using this release and see if it fixed your problem..

https://github.com/reactiveui/splat/releases/tag/14.1.58

**Comment by RejectKid** [comment]
![image](https://user-images.githubusercontent.com/6117898/161602853-52f0a0b6-233e-48ff-bfb9-4f3cb4a24307.png)

I dont believe it did.
so here's what happens on startup of the app
as soon as the registration occurs the view is newed up (and naturally the DataContext is null)

**Comment by RejectKid** [comment]
how goes this guy? :-)

**Comment by dpvreony** [comment]
can you confirm your view isn't decorated with

```
[SingleInstanceView]
```

**Comment by dpvreony** [comment]
reproduced with     [ViewContract("somecontract")]

**Comment by dpvreony** [comment]
turns out loads of unit tests are not checking splat usage of DryIoC. currently it's all single instance because it invokes the factory at registration. if you don't do that it won't cast because the factory is a Func<object> which DryIoC can't resolve to the servicetype. it's going to take some unpicking.

**Comment by RejectKid** [comment]
correct it doesnt have the decorator
