### ISSUE TITLE
[BUG] Getting dependency from DryIoC container creates dependency object twice

### ISSUE THREAD

**Issue by scheidtdav** [reactiveui/splat#890]
**Describe the bug**
When using a DryIoC container with Splat, calling `Locator.Current.GetService<MyViewModel>()` leads to two `MyViewModel` objects being created.
The same goes for ReactiveUIs view locator, which resolves `IViewFor<MyViewModel>` twice thus creating two instances of a view.
This can have a negative impact on performance and lead to unexpected behavior.

**Steps To Reproduce**
```
var container = new Container();
container.UseDryIocDependencyResolver();
container.Register<MyViewModel>();

// Using a breakpoint in the MyViewModel constructor
// it can be observed that it is created twice.
var vm = Locator.Current.GetService<MyViewModel>();
```

**Expected behavior**
Resolving a dependency should not lead to multiple objects of the resolved type being instantiated.

**Screenshots**
-

**Environment(please complete the following information):**
 - OS: Android
 - Version: 10 (EMUI 12)
 - Device: Huawei P40 Lite 5G

**Additional context**
I think I narrowed down the problem to the behavior of Enumerables in `DryIocDependencyResolver`, though I am not sure how to fix it.
In its `GetServices` implementation, the `Any()` method is called, which iterates the Enumerable and therefore instantiates the object the first time.
https://github.com/reactiveui/splat/blob/9636f354928f0862f300004b9d5f8678a93d496f/src/Splat.DryIoc/DryIocDependencyResolver.cs#L47

Afterwards the original Enumerable is returned to the `GetService` implementation, where `LastOrDefault()` iterates the enumerable again, creating another object.
https://github.com/reactiveui/splat/blob/9636f354928f0862f300004b9d5f8678a93d496f/src/Splat.DryIoc/DryIocDependencyResolver.cs#L34

This was reproducible for me by using the container directly to verify this behavior like so:
```
var fromContainer = container.ResolveMany(typeof(MyViewModel), serviceKey: null);
if (fromContainer.Any()) // after this call, MyViewModel constructor is called
    _ = fromContainer.LastOrDefault(); // after this call, MyViewModel constructor is called again
```

I tried reproducing it in a unit test, but this might be prevented from happening by [.NET6.0 LINQ improvements](https://www.infoq.com/news/2021/04/Net6-Linq/), especially the [`TryGetNonEnumeratedCount`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.trygetnonenumeratedcount?view=net-6.0) which is likely being used by the `Any()` call.

One idea would be to pass `ResolveManyBehavior.AsFixedArray` to the `ResolveMany()` call. But I am uncertain if this would fix the issue.

Any ideas? Does anybody else have this issue?

**Comment by glennawatson** [comment]
One way is it implement https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Linq/src/System/Linq/Count.cs#L96 for non 6 platforms

**Comment by glennawatson** [comment]
I'm very time limited at the moment but if I get time I'll fix this on the weekend. @dpvreony may also have time to help out on this one.

**Comment by glennawatson** [comment]
This may be related to #889 as well

**Comment by scheidtdav** [comment]
Hey, thanks for the quick reply.

I tried using a custom `IDependencyResolver` inheriting from `DryIocDependencyResolver` to set `ResolveManyBehavior.AsFixedArray` in the `ResolveMany()` call.
This seems to work fine. The duplicate calls are gone as far as I can tell.
Since (as described) the `LastOrDefault` call iterates the enumerable anyways, this shouldn't add any additional resource usage.

If this would be a valid fix, I am happy to submit a PR.
Not sure how to trigger this behavior in a unit test though, they seem to run using .NET 6...

**Comment by glennawatson** [comment]
I guess this could be an argument to bring back net48 target framework to the tests

**Comment by scheidtdav** [comment]
Turns out I must have done something wrong, when I first tried it with net6.
It was indeed reproducible, so I filed a PR with a test and fix. No need to bring back net48 (although I tried and it didn't change anything).

**Comment by glennawatson** [comment]
There has been a release https://github.com/reactiveui/splat/releases/tag/14.1.58

Thanks for the help.
