### ISSUE TITLE
Default Test and Run mode

### ISSUE THREAD

**Issue by adamradocz** [reactiveui/splat#938]
**Is your feature request related to a problem? Please describe.**
Kent Boogaart in the "You, I, and ReactiveUI" book recommends overriding the `ModeDetector` in order to boost its performance. But implementing the same `CustomModeDetector` in every project is a little bit cumbersome.

**Describe the solution you'd like**
The default implementation of the Run and Test mode.

**Example:**

```csharp
public sealed class Mode : IModeDetector
{
    private readonly bool _inUnitTestRunner;

    public static readonly Mode Run = new(false);
    public static readonly Mode Test = new(true);

    private Mode(bool inUnitTestRunner)
    {
        _inUnitTestRunner = inUnitTestRunner;
    }

    public bool? InUnitTestRunner() => _inUnitTestRunner;
}

```

**Usage in the Run environment:**

```csharp
public App()
{
    Splat.ModeDetector.OverrideModeDetector(Mode.Run);
    
    //... the rest of the startup code.
}
```

**Usage in the Test environment:**

```csharp
Splat.ModeDetector.OverrideModeDetector(Mode.Test);
```

I can make a PR if you like this solution.

**Comment by glennawatson** [comment]
Sounds like a good PR. Doesn't break existing functionality. Go for it.

**Comment by adamradocz** [comment]
@glennawatson @ChrisPulman 
I've been thinking about the naming of `Mode.Run` and it feels a little bit clumsy.
Wouldn't the `Mode.App` be better, or the `Mode.Run` is just fine?

**Comment by anaisbetts** [comment]
> recommends overriding the ModeDetector in order to boost its performance.

I guess I question this a bit - if ModeDetector is slow, why don't we just fix it? That seems better than trying to make "official workarounds" for our own code!

**Comment by glennawatson** [comment]
Probably can make it faster for newer SDK style applications .net 6 and above, since there are now "UseWindowsForms" and "UseWPF" and "Maui msbuild properties. Older framework applications we still support have no such joy.

**Comment by glennawatson** [comment]
I'll make an issue so we can target those properties at the very least to give the user a speed boost in those environments.

**Comment by glennawatson** [comment]
https://github.com/reactiveui/splat/issues/940

**Comment by adamradocz** [comment]
`ModeDetector` uses reflection in order to detect the environment. No matter how you optimize it, it's always going to be a magnitude slower than a predefined method that just returns `true` or `false`.
