### ISSUE TITLE
Bitmap Save() on WinRT throwing up when using PNG

### ISSUE THREAD

**Issue by promontis** [reactiveui/splat#95]
Hi Paul!

Was trying out Splat... while using Bitmap.Save() I got a nasty exception (COM exception giving no information whatsoever)... after debugging I figured out that the ImageQuality encoding property is not supported when using the PNG format. For a list of supported shizzle... see: https://msdn.microsoft.com/en-us/library/windows/apps/jj218354.aspx

It seems the ImageQuality is only supported when using JPG. I confirmed this when switching to saving to JPG format... it works! 

If I find some spare time, I'll create a PR for this. Do you agree that the fix is to not use the ImageQualtity when PNG is selected? So introduce a variable for the list of encoding options. An if-statement to check if JPG, and if so, add the image qualtity option. Otherwise, it will just be the empty list of encoding options

**Comment by paulcbetts** [comment]
Seems legit, though I think the better fix is to never use WinRT for anything ever, but I'm biased :)
